### ISSUE TITLE
Error when using metadata past your actual amount

### ISSUE THREAD

**Issue by EnabledEnzo** [11matt556/DSP-ReusableMetadata#2]
got this error after I used more meta data than I have. Another issue talked about basically infinite metadata which is still an issue and that's how I got this error.
Steps to reproduce:

1. start a new game with bepin ex and reusable metadata installed
2. use metadata on every thing you can till you know you've spent more than you own
3. click the metadata info screen in the upper right of technologies
![DSPGAME_IWFY4HbtiW](https://user-images.githubusercontent.com/78254847/173710123-df60199b-9841-4106-a00d-84b022d332ee.png)
.

**Comment by 11matt556** [comment]
Looks like the same root cause as issue #1. See my comment there for details but should be able to fix it soon.

**Comment by 11matt556** [comment]
Just pushed version 1.0.5 which should hopefully fix this. Let me know if you get a chance to test it.

**Comment by 11matt556** [comment]
Closing since this _should_ be fixed in 1.0.5 and I haven't heard back. Let me know if you still have any problems.
